### ISSUE TITLE
mem囧TZ 公益宣言申请

### ISSUE THREAD

**Issue by mem0rz** [Nonprofit-Minecraft/Certification#10]
必要信息
mem囧TZ 公益服 主要负责人QQ：3452389034
QQ群：837166365
您如果有兴趣可以去看一下我们的论坛：bbs.memotz.com

现时状况
服务器是一个SPONGE模组服，24小时平均在线0.5人。memotz是一个无审核机制的服务器，任何人都可以进入服务器玩耍，服务器目前处在建设初期很多东西还不完善，如有心一起建设请联系
模组服嘛，每周基本都有加模组删模组的计划，希望玩家能积极参与服务器的管理讨论提供有建设性的意见。本服务器没有任何充值点，如果有捐赠我会相对应的改善服务器设施
另外会用于招聘建筑师、和熟悉SPONGE的管理员。发工资的那种

条件确认
本服绝对遵循公约全部要求
本服务器符合「Minecraft 公益服务器宣言」的公益服务器标准。
https://bbs.memotz.com/viewtopic.php?f=3&t=5
https://bbs.memotz.com/viewtopic.php?f=3&t=4

封面图片
请提供用于展示的封面图片，大小要求854x480，不提供则使用公益宣言标志
![QQ图片20190504162949](https://user-images.githubusercontent.com/14276116/57177166-164ef800-6e94-11e9-8cef-fd6dc81e0b7a.png)

介绍文本
请提供用于展示的介绍文本，不超过一句话
1年2年甚至5年10年我们只想建设一个能承载大家回忆的地方，不管有不有人玩服务器永远不会关闭，数据永远保存，这是目前服务器已有的一群咸鱼史蒂夫的共识~

外部链接
请提供用于展示跳转的链接地址，例如服务器官网
https://bbs.memotz.com/viewforum.php?f=1
https://minecraft.memotz.com:8888

其他信息
你可以在此补充你想提供的其他信息

**Comment by mem0rz** [comment]
![QQ截图20190504172545](https://user-images.githubusercontent.com/14276116/57181641-17e6e300-6ec9-11e9-9887-c420c086fd68.png)
服务器首次创建密码文件时间戳

**Comment by sotr2333** [comment]
申請已通過
