### ISSUE TITLE
SakuraFall丨桜落坊 申请

### ISSUE THREAD

**Issue by NyanMeow** [Nonprofit-Minecraft/Certification#11]
**必要信息**
*请在此填写服务器的必要信息，例如服务器名称、联系方式、介绍网页。*
名字：SakuraFall 桜落坊 联系方式(QQ)974204879 网页在做
 
**现时状况**
*请在此介绍服务器目前的状况，例如在线情况、申请原因*
当前处于周目更换时期，以往周目在线大约5-10人 申请原因：4年公益服，可以对我们放心

**条件确认**
*请确保你的服务器已经遵循公约的全部要求*
符合√
**封面图片**
*请提供用于展示的封面图片，大小要求854x480，不提供则使用公益宣言标志*
![QQ20190515195842e0043.png](https://miao.su/images/2019/05/15/QQ20190515195842e0043.png)
**介绍文本**
*请提供用于展示的介绍文本，不超过一句话*
SakuraFall丨一只小喵喵的养成之处w  养老丨原版轻RPG丨正版
**外部链接**
*请提供用于展示跳转的链接地址，例如服务器官网*
暂无

**Comment by sotr2333** [comment]
申請已通過
