### ISSUE TITLE
OurWorld

### ISSUE THREAD

**Issue by smyhw** [Nonprofit-Minecraft/Certification#3]
必要信息 
名称：OurWorld | 联系方式：QQ: 3234570937 | 服务器木得网站
现时状况 
服务器运行稳定，不过小服务器，一般在线人数不稳定
主要还是为了适当的宣传2333
条件确认 我确保OurWorld服务器已经遵循公约的全部要求
封面图片 
https://github.com/smyhw/ourworld/blob/master/awa.png
介绍文本 OurWorld，和谐的原版公益服务器
外部链接 服务器木得网站，宣传见群公告及服务器出生点

**Comment by sotr2333** [comment]
申请已经通过。
