### ISSUE TITLE
RIA iBS公益宣言申请

### ISSUE THREAD

**Issue by ghost** [Nonprofit-Minecraft/Certification#4]
**必要信息**
RIA iBasyo    主要负责人QQ：1908633182     
您如果有兴趣可以去看一下我们的宣传贴：http://www.mcbbs.net/thread-850649-1-1.html

**现时状况**
服务器因为是ria系模组服，我们本身对模组服就没有经验，这可以说是一次新的探索。
模组服永远有处理不完的bug，但是我们一直在背后进行着夜以继日的协调与筹整。
目前在线情况平均可达10+ 这也是一件令人欣慰的事，看着这些加入RIA的玩家，
读着他们与MC之间的故事，这是令我们继续下去最大的动力。

**条件确认**
本服绝对遵循公约全部要求
本服务器符合「Minecraft 公益服务器宣言」的公益服务器标准。

**封面图片**
*请提供用于展示的封面图片，大小要求854x480，不提供则使用公益宣言标志*
![新](https://user-images.githubusercontent.com/48977182/55053998-2572a700-5099-11e9-82db-138b33a0ea39.png)

**介绍文本**
*请提供用于展示的介绍文本，不超过一句话*
没有你的世界，不是我的世界。

**外部链接**
*请提供用于展示跳转的链接地址，例如服务器官网*
http://www.mcbbs.net/thread-850649-1-1.html

**其他信息**
*你可以在此补充你想提供的其他信息*
IBS是一个设有一定审核机制的服务器。我们并不想无节制地扩张人数，我们只想找到一个令老成员有所留念，令新成员有所归属的环境平衡。在此由衷地感谢公益宣言对我们给予的支持。

**Comment by ghost** [comment]
![TJH}CAO~`GD%LI~ PYS `E9](https://user-images.githubusercontent.com/48977182/55053704-0293c300-5098-11e9-9edc-2dbc1440b35b.jpg)

**Comment by ghost** [comment]
![Q}GWPL22U` 3U_)K~{ZV {B](https://user-images.githubusercontent.com/48977182/55053716-09223a80-5098-11e9-9b45-178bd5343c80.png)

**Comment by sotr2333** [comment]
认证申请已通过。
