### ISSUE TITLE
私立⑨学院 公益宣言申请

### ISSUE THREAD

**Issue by HongCha123** [Nonprofit-Minecraft/Certification#5]
**必要信息**
服务器名称:私立⑨学院（Cirnocraft）
主要负责人QQ:1003195137
服务器宣传贴：http://www.mcbbs.net/thread-689103-1-1.html
（虽然简短）

**现时状况**
服务器目前稳定，由于是小服务器，在线人数并不是很稳定

**条件确认**
私立⑨学院已符合公约要求以及公益宣言的标准

**封面图片**
*请提供用于展示的封面图片，大小要求854x480，不提供则使用公益宣言标志*
https://i.loli.net/2019/03/27/5c9b72fbd5055.png

**介绍文本**
和谐的原版与空岛生存服务器。

**外部链接**
https://jq.qq.com/?_wv=1027&k=56NtXzi

**其他信息**
传说，服务器有个神奇的指令，叫/e

**Comment by sotr2333** [comment]
缺少公约披露，请在群公告，宣传贴，客户端等地披露公约，详见Documents/服主手册

**Comment by HongCha123** [comment]
补图披露证明
https://i.loli.net/2019/03/29/5c9e25ff07655.png

**Comment by sotr2333** [comment]
申请已通过
