### ISSUE TITLE
WhiteG白鲸物语 公益宣言申请

### ISSUE THREAD

**Issue by moewhite19** [Nonprofit-Minecraft/Certification#6]
**必要信息**
*请在此填写服务器的必要信息，例如服务器名称、联系方式、介绍网页。*
WhiteG白鲸物语
[加群链接](https://shang.qq.com/wpa/qunwpa?idkey=721e67fccb301fc7dea9308ae200bc8b64a2c101f76b7fcaf4ed24714ed22bfb)
暂无官网

**现时状况**
*请在此介绍服务器目前的状况，例如在线情况、申请原因*
服务器与去年中旬建设，目前日在线五人左右

**条件确认**
*请确保你的服务器已经遵循公约的全部要求*
本服务器符合并且遵守着「Minecraft 公益服务器宣言」的公益服务器标准。

**封面图片**
*请提供用于展示的封面图片，大小要求854x480，不提供则使用公益宣言标志*
![log](https://user-images.githubusercontent.com/27201604/55245407-097c2a80-527e-11e9-8a64-8d23139de75f.jpg)

**介绍文本**
*请提供用于展示的介绍文本，不超过一句话*
轻RPG生存养老服

**外部链接**
*请提供用于展示跳转的链接地址，例如服务器官网*
[https://www.mcmod.cn/play/sv/20181618.html](https://www.mcmod.cn/play/sv/20181618.html)
**其他信息**
*你可以在此补充你想提供的其他信息*
将公益进行到底

**Comment by sotr2333** [comment]
已通過
