### ISSUE TITLE
NaturalWorld公益宣言申请

### ISSUE THREAD

**Issue by NaturalWorldToAsT** [Nonprofit-Minecraft/Certification#7]
**必要信息**
NaturalWorld主要负责人 QQ：2229423845
（逗比吐司要隐退了所以留了夙夜哥哥的）
**现时状况**
NaturalWorld是一个秉承原版的玩家社区
（也是一个命运多舛的服务器）
从历史来算已经三度危机（一年半）
管理组秉承着“玩家体验至上”的理念
几周前被勒索病毒打了，损失惨重（真正的勒索病毒真香）
近期我们开放了魔法冒险服，未来会恢复工业mod服
技术夙夜每天都抱着他的电脑快乐的处理服务器疑难杂症
目前在线因为受到被攻击事件的牵连……也就3+吧
我们希望NTW是一个可以给大家快乐的玩家社区
**条件确认**
*请确保你的服务器已经遵循公约的全部要求*
本服绝对遵循公约全部要求
本服务器符合「Minecraft 公益服务器宣言」的公益服务器标准
**封面图片**
*请提供用于展示的封面图片，大小要求854x480，不提供则使用公益宣言标志*
![2019-02-22_12 06 19_meitu_2](https://user-images.githubusercontent.com/49005863/55275540-a55f7200-5322-11e9-812d-8390ec793b96.jpg)

**介绍文本**
*请提供用于展示的介绍文本，不超过一句话*
欢迎各位来到我们的大家庭哦~
**外部链接**
*请提供用于展示跳转的链接地址，例如服务器官网*
没做好的官网 http://mi-an.top/
**其他信息**
*你可以在此补充你想提供的其他信息*
欢迎各位dalao入驻服务器，服内常有dalao出没，请准备好大师球desu~

**Comment by sotr2333** [comment]
未发现进行公约披露。

**Comment by NaturalWorldToAsT** [comment]
> 未发现进行公约披露。

同志，我们已经做足了公约的所有披露，无论是在客户端内还是在群公告内，官网因为没有做完（才做了个首页）……我也是NPSCO成员……

**Comment by sotr2333** [comment]
申请已通过。
