### ISSUE TITLE
时忆（Timory）宣言申请

### ISSUE THREAD

**Issue by ghost** [Nonprofit-Minecraft/Certification#9]
**必要信息**
服务器名称: 时忆（Timory）
负责人 Chi_Hun  QQ：1833537796

管理团队(排名不分先后)：

- Chi_Hun 运营事务管理
- Ayu__ 白名单审核/玩家管理
- Leo_Maxwell 日常运维
- ShirosakiMieru 日常运维/插件开发/技术支持
- Stealth_Feather 活动策划/建筑
- Miao_Pass 服务器提供、托管
- IceLocke 插件开发/技术支持
- Sealoong 插件开发/技术支持

加入方式:
QQ群: 369362516

**现时状况**

(截止19/04/10)
运营时长:   2016/06/13至今
运行状况：开放中
在线人数：日常1~15人左右
群内人数：450+ 

**条件确认**
本服已遵循公约全部要求
本服务器符合「Minecraft 公益服务器宣言」的公益服务器标准

服务器管理员 ShirosakiMieru (GitHub账户:FlanNep) 参与了公益宣言的制定，作为组织Nonprofit-Minecraft的Member之一，提交过PR。

**封面图片**
![](https://i.loli.net/2019/05/03/5ccbced666d5a.png)

**介绍文本**
时忆（Timory）致力于打造国内高素质玩家社区，欢迎你的加入～(￣▽￣～)~

**外部链接**

- 官网：https://www.mcshiyi.com
- 博客：https://www.mcshiyi.com/blog
- GitHub(时忆开源中心): https://github.com/TimoryGroup
- Telegram交流群: https://t.me/mcshiyi

**其他信息**

时忆（Timory）服务器致力于打造国内高素质的正版玩家社区，在此时忆永远欢迎各位高素质的正版玩家加入我们，与我们一道实现这个目标。时忆自2016年开服以来，已入驻上百位志同道合的玩家，这里是热爱Minecraft的我们共同的家园。时忆将会尽最大的努力，将我们美好的过去与无限的未来交织，引领您畅游这自由的国度！

注: 入服要求

1. 拥有国际(Java版)正版账号
2. 遵守服务器规定：https://www.mcshiyi.com/rules 
3. 建议15岁及以上
 如您确定以及肯定能够做到以上规则并拥有国际版Minecraft账户，我们非常欢迎您的加入！

**Comment by ghost** [comment]
群内公告:  
![QQ图片20190411081240.jpg](https://i.loli.net/2019/04/11/5cae868b882cc.jpg)

**Comment by sotr2333** [comment]
申請已通過
